### ISSUE TITLE
Telegram not working in v3.0.0-rc.4

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-cli#90]
```
   • Running test nettests.Telegram
   ⨯ Failed to run Instant Messaging error=no such field
```
